# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.ScheduleResourceRelationships do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :trip,
    :stop,
    :route,
    :prediction
  ]

  @type t :: %__MODULE__{
    :trip => MBTA.Model.ScheduleResourceRelationshipsTrip.t | nil,
    :stop => MBTA.Model.ScheduleResourceRelationshipsStop.t | nil,
    :route => MBTA.Model.ScheduleResourceRelationshipsRoute.t | nil,
    :prediction => MBTA.Model.ScheduleResourceRelationshipsPrediction.t | nil
  }

  alias MBTA.Deserializer

  def decode(value) do
    value
     |> Deserializer.deserialize(:trip, :struct, MBTA.Model.ScheduleResourceRelationshipsTrip)
     |> Deserializer.deserialize(:stop, :struct, MBTA.Model.ScheduleResourceRelationshipsStop)
     |> Deserializer.deserialize(:route, :struct, MBTA.Model.ScheduleResourceRelationshipsRoute)
     |> Deserializer.deserialize(:prediction, :struct, MBTA.Model.ScheduleResourceRelationshipsPrediction)
  end
end

