# NOTE: This file is auto generated by OpenAPI Generator 7.1.0 (https://openapi-generator.tech).
# Do not edit this file manually.

defmodule MBTA.Model.StopResourceAttributes do
  @moduledoc """
  
  """

  @derive Jason.Encoder
  defstruct [
    :wheelchair_boarding,
    :vehicle_type,
    :platform_name,
    :platform_code,
    :on_street,
    :name,
    :municipality,
    :longitude,
    :location_type,
    :latitude,
    :description,
    :at_street,
    :address
  ]

  @type t :: %__MODULE__{
    :wheelchair_boarding => integer() | nil,
    :vehicle_type => integer() | nil,
    :platform_name => String.t | nil,
    :platform_code => String.t | nil,
    :on_street => String.t | nil,
    :name => String.t | nil,
    :municipality => String.t | nil,
    :longitude => float() | nil,
    :location_type => integer() | nil,
    :latitude => float() | nil,
    :description => String.t | nil,
    :at_street => String.t | nil,
    :address => String.t | nil
  }

  def decode(value) do
    value
  end
end

